### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'url_for' is undefined when using recipe.template

### ISSUE THREAD

**Issue by schnitzelbub** [bocadilloproject/bocadillo#111]
**Expected behavior**
Templates (e.g. methods `template` or `template_string`) should work on `Recipe` objects like on `API` objects.  

**Actual behavior**
A `jinja2.exceptions.UndefinedError` is raised when trying to use e.g. `url_for` calling `recipe.template()`.

**To Reproduce**

1. Run this application code:

```python3
import bocadillo
from bocadillo import Recipe

tacos = Recipe("tacos", prefix="/tacos")
api = bocadillo.API()


@tacos.route("/home")
async def home(req, res):
    res.html = "<html><body>HOME</body></html>"


TEMPLATE = """
<html>
<body>
    <div>PARENT: {{ parent }}</div>
    <div>URL: {{ url_for('tacos:home') }}</div>
</body>
</html>
"""

@tacos.route("/template/recipe/")
async def retrieve_template_recipe(req, res):
    res.html = tacos.template_string(TEMPLATE, parent="recipe")


@tacos.route("/template/api/")
async def retrieve_template_api(req, res):
    res.html = api.template_string(TEMPLATE, parent="api")

api.recipe(tacos)

if __name__ == "__main__":
    api.run()
```
2. Accessing "http://localhost:8000/tacos/template/api/" returns expected page:

```html
<html>
<body>
<div>PARENT: api</div>
<div>URL: /tacos/home</div>
</body>
</html>
``` 
3. Accessing "http://localhost:8000/tacos/template/recipe/" throws:
```
  File "<template>", line 5, in top-level template code
jinja2.exceptions.UndefinedError: 'url_for' is undefined
```

**Specs**
- OS: Linux 4.20 x86_64
- Python Version: 3.7.2
- Bocadillo Version:  0.10.1

**Comment by florimondmanca** [comment]
I was going to ask for tracebacks or a minimal setup to replicate but you've just updated, so thanks for that. :-)

After looking at it, `url_for` is indeed not made available to the template environment of recipes, but it should be. Looks like there's also some refactoring required to make that happen (because the `API` and `Recipe` objects do not store HTTP routes the same way).
