### ISSUE TITLE
Automatic trailing slashes

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#167]
**Is your feature request related to a problem? Please describe.**
Currently, route matching honours whether the URL pattern contains a trailing slash or not.

For example:

- The `/foo` URL pattern matches `/foo` but *not* `/foo/`.
- Likewise, `/foo/` matches `/foo/` but *not* `/foo`.

**Describe the solution you'd like**
There should be an option to support both versions (w/ and w/o the trailing slash), and it should be the default behavior. The framework user could turn it off (globally or on a per-route basis) in order to turn off exact match.

**Describe alternatives you've considered**
/

**Implementation ideas**

Introduce an `auto_trailing_slash` option on `BaseRouter` (and on `App`) and `BaseRoute`, defaulting to `True`, which would do the following:

- If the URL pattern does not end with a trailing slash, add one.
- If the requested URL path does not end with a trailing slash, add one — but *do not* perform a 301 redirection, because that would lose form data and some special headers.

**Additional context**
/

**Comment by heykarimoff** [comment]
@florimondmanca I want to give a shot on this

**Comment by florimondmanca** [comment]
Sounds good!

As for the last bullet point in the issue, I think we should actually redirect if the client requests /foo but the route is actually /foo/. I’m not sure why I said we would lose POST data or headers doing so. That said, CORS would definitely not work in case of redirection (not supported by the standard) so we should probably document that somewhere in the routing documentation. We can totally think about that later on. :-)

**Comment by florimondmanca** [comment]
Hey, any luck on this @heykarimoff? If you've tried something out and want to share some insights and perhaps any difficulties you've encountered, feel free to do so!

**Comment by heykarimoff** [comment]
> Sounds good!
> 
> As for the last bullet point in the issue, I think we should actually redirect if the client requests /foo but the route is actually /foo/. I’m not sure why I said we would lose POST data or headers doing so. That said, CORS would definitely not work in case of redirection (not supported by the standard) so we should probably document that somewhere in the routing documentation. We can totally think about that later on. :-)

I agree on. I looked at the source codes of Django & Flask and they also redirect to trailing slashed path.

> Hey, any luck on this @heykarimoff? If you've tried something out and want to share some insights and perhaps any difficulties you've encountered, feel free to do so!

Thanks you, I have push my changes to [this branch](https://github.com/heykarimoff/bocadillo/tree/auto_trailing_slash) please have a look✋. 

Current challenges are:
- Where to add `AUTO_TRAILING_SLASH` global setting
- How to deal with WebSocketRouter

**Comment by florimondmanca** [comment]
Thanks! Hope you enjoyed your trips. :-)

Can you open a PR so we can view and discuss the changes more easily? 👍

**Comment by florimondmanca** [comment]
Hi @heykarimoff, I've just realised that the change on your branch is very easy to look at — sorry for not responding earlier.

I think it looks good, and I think we can try to merge this before #271 goes through, as it contains a large refactoring of the routing implementation, and it's easier to bring changes back to there than the other way around.

Anyway, as for the challenges you mentioned:

> - Where to add AUTO_TRAILING_SLASH global setting

May I suggest creating a [plugin](https://bocadilloproject.github.io/guide/plugins.html)? It would allow people to configure that via the settings module.

> - How to deal with WebSocketRouter

I'd suggest we don't worry about that now. I can get this fixed when this is brought back into #271.

**Comment by florimondmanca** [comment]
@heykarimoff Just so you know, I pushed an implementation of this in #271, as I would like to get this merged and released for 0.16 soon. See the code [here](https://github.com/bocadilloproject/bocadillo/pull/271/files#diff-2c4c7e77507caef4dc1c06c6b50ed3d5R217).

Thanks for your contribution on this, and sorry again to have let this hang for too long!
