### ISSUE TITLE
Dependency injection/resource provisioning

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#170]
**Is your feature request related to a problem? Please describe.**

I was trying to integrate with [Databases] in my [personal API rewrite][personal-api-bocadillo]. I previously managed to integrate [Tortoise], but Databases works differently.

- Tortoise does not require to hold a reference to the database. Instead, we manipulate models directly, which are typically imported from a dedicated module.
- On the other hand, Databases requires to keep a reference to the db in order to execute the queries: `await db.fetch_all(animals.select())`.

At a higher-level, there is currently no easy way to implement reusable services or resources in order to de-clutter views. People may be tempted to use middleware for that purpose, or abuse lifespan handlers. *There must be a better way.*

**Describe the solution you'd like**

Take inspiration from [Pytest fixtures] and implement a simple dependency injection system.

The implementation is already done via [aiodine], so this will only require some glue code and documentation.

Here is how this should allow to integrate with [Databases]:

```python
from bocadillo import App, provider
from databases import Database
from models import notes

app = App()

@provider(scope="app")
async def db():
    async with Database("sqlite://:memory:") as database:
        yield database

@provider
async def notes(db):
    return [
        {"id": note.id, "content": note.content}
        async for note in db.iterate(notes.select())
    ]

@app.route("/")
async def index(req, res, notes):
    res.media = notes
```

**Describe alternatives you've considered**

- Let framework users set arbitrary attributes on `app`, e.g. `app.db`: this is longer to type, not type annotation-friendly, and too rigid.
- Allow to set arbitrary attributes on `req` (e.g. using `req.state` that comes with Starlette v0.11): it would only work in HTTP views. In the example above, it wouldn't have been possible to use the database in a WebSocket view. In short, some (many?) providers are not tied to the HTTP protocol, so we need to handle them at a higher level.
- Non-function-based provider registration, i.e. `app.provider(name=value)`: besides allowing many less features, this may allow to register providers whose name is not a valid Python identifier, which makes them unusable in views. In the name of "There should be one, and only one obvious way to do it", let's stick to a function-only API.
- `resource` instead of `provider`: the term "resource" may be confusing to people coming from the world of REST APIs.
- `fixture` instead of `provider`: the term "fixture" would have been *very* confusing to people coming from Django or pytest (which have their own distinct concept of fixtures).
- `ingredient` instead of `provider`:  too much metaphor hinders developer productivity.

**Additional context**

- [Personal API rewrite with Bocadillo][personal-api-bocadillo]
- [Tortoise ORM][tortoise]
- [Databases]
- [Pytest fixtures]

[personal-api-bocadillo]: https://github.com/florimondmanca/personal-api-bocadillo
[tortoise]: https://tortoise-orm.readthedocs.io
[databases]: https://github.com/encode/databases
[pytest fixtures]: https://docs.pytest.org/en/latest/fixture.html
[aiodine]: https://github.com/bocadilloproject/aiodine

**Comment by Marlysson** [comment]
Do your plan is provide a "pre fetched data" as a fake server like that?

https://github.com/typicode/json-server

Or Am I wrong?

**Comment by florimondmanca** [comment]
@Marlysson I'm not sure I fully understood what you meant by "pre-fetched data", but I don't think that's the idea behind fixtures. :)

Fixtures would be a generic way to inject resources/dependencies into views. So if you want to provide views with a fake server, I think you could do so with a *yield fixture* that fires off a separate process for the server and shuts it down on cleanup.

For example:

```python
import os
import signal

from fake import start_fake_server

@fixture
def fake_server():
    pid = start_fake_server()
    yield
    os.terminate(pid, signal.SIGTERM)
```

Is that the use case you were thinking about?

**Comment by Marlysson** [comment]
I think so...

Cause I was reading about your concept around fixtures and came in my head (  because your examples was ever using objects pre-propulated ) the fixtures used in Django to tests..

But reading more about its documentation I'm beginning  to understand.. 

It's more related to dependency injection either data or classes in runtime execution.. 

Why do you handle more with data than objects as dependency injection ?

**Comment by florimondmanca** [comment]
I forgot about Django’s fixtures! I can see why using the same word may be misleading :-) Indeed, Django’s fixtures are about providing initial data to populate the database with, whereas here fixtures don’t even have anything to do with tests at all.

I guess the fact that I mention that they are inspired by pytest’s fixtures doesn’t help to understand this either. This feature is indeed like a runtime DI system. In a sense, only the design comes from pytest, not the usage.

> Why do you handle more with data than objects as dependency injection ?

Here, DI is used in a more general way than the OOP creational pattern (which I suppose you’re referring to?). It’s more the idea of « hey, I need whatever object/function/data structure that has been register under this name, please inject it in here » than « hey, can you build an instance of this class for me please? ». That’s something coming from pytest, and in a testing context it’s easy to understand why one needs testing *data* (in general) rather than just testing *objects*.

---

Anyway, do you think the docs aren’t clear enough about how this feature is not about testing, nor providing test or mock data? It’s very possible! The term « fixture » is used by many to mean different things...

In fact, I was thinking about calling these *ingredients* instead of fixtures, in order to have a separate word that also better reflects what they are: small components that you can build upon to make your views and stuff. What do you think? :-)

**Comment by Marlysson** [comment]
Very clear explanation. 

I confused the concepts.. How I came from Django this concept it's related ( a salad of concepts haha ) .

Throughout the reading of the documentation I started understand the concept.

> In fact, I was thinking about calling these _ingredients_ instead of fixtures, in order to have a separate word that also better reflects what they are: small components that you can build upon to make your views and stuff. What do you think? :-)

Whole framework around the concepts of food .. cool . But you plan the people use this framework with components being a funny name? Nothing against.

**Comment by florimondmanca** [comment]
> But you plan the people use this framework with components being a funny name?

😆 Well, I think as long as the name is descriptive enough (as I said, I think *ingredient* is quite explicit), and we justify *why* we're choosing a metaphorical name over a more common one (here: to prevent confusion with other similarly-named but totally different features in other frameworks), we should be fine.

I'm not sold yet on this myself, but that's definitely an option. Consider what would happen for people testing Bocadillo apps with pytest? Two things named "fixtures" with the same API — how do you know which is which?

**Comment by Marlysson** [comment]
I agree totally.

**Comment by florimondmanca** [comment]
Thought about it again. It turns out calling it *ingredients* may be too much metaphor. I'd rather have people use a somewhat dull name and be efficient that wonder "Okay, so what is an ingredient exactly again?" every time they stumble upon the word. What convinced me was that *I* as a maintainer have had a hard time not suffering from a slight cognitive load while reading "ingredient". It's called dependency injection, so let's stick to *providers* that *inject* resources into *consumers* (= views). :+1:

**Comment by Marlysson** [comment]
Awesome!!!
