### ISSUE TITLE
Explain how to deploy to Heroku

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#177]
**Is your feature request related to a problem? Please describe.**
For Heroku users, or people who want to quickly deploy a Bocadillo app, it would be nice to have some hints as to how to deploy on Heroku.

**Describe the solution you'd like**
- Add a How-To guide (in `/docs/how-to/`) explaining how to publish a "Hello, world" Bocadillo app to Heroku, step by step, and what the limitations are.
- Add a link to it in the [Deployment discussion](https://bocadilloproject.github.io/discussions/deployment.html).

**Describe alternatives you've considered**
- Cram everything into a new section of the Deployment discussion, but this is really a cooking recipe, hence this should be a How-To.

**Additional context**
[Contributing documentation](https://github.com/bocadilloproject/bocadillo/blob/master/CONTRIBUTING.md#contributing-documentation)

**Comment by heykarimoff** [comment]
@florimondmanca I'm going to give a try on this.

**Comment by florimondmanca** [comment]
Great! Looking forward to it .💯

**Comment by heykarimoff** [comment]
Just deployed `bocadillo` powered app on heroku at https://bocadillo-app.herokuapp.com. It works wonderfully 🎉.
Here is the app repo https://github.com/heykarimoff/bocadillo_app.

I am going to write a documentation and send a PR soon.

**Comment by florimondmanca** [comment]
Well done @heykarimoff!

If you want, I can create a new `heroku-example` repo on the organization, give you commit access and you can push the code there, so that the project is more easily discoverable and placed along side the other example projects ([docker-example](../../docker-example), [bloguero](../../bloguero), etc). What do you think? 😊

**Comment by florimondmanca** [comment]
By the way, did you try to deploy without setting `port=int(os.getenv("PORT"))`? As explained [here](https://bocadilloproject.github.io/guides/app.html#host-and-port), if the `$PORT` environment variable is set Bocadillo will use it along with `0.0.0.0` as the port. I configured it that way because in my memories this is what Heroku expects, but if that's not the case then we can consider it a bug. :wink:

**Comment by heykarimoff** [comment]
> Well done @heykarimoff!
> 
> If you want, I can create a new `heroku-example` repo on the organization, give you commit access and you can push the code there, so that the project is more easily discoverable and placed along side the other example projects ([docker-example](../../docker-example), [bloguero](../../bloguero), etc). What do you think? 😊

Yeah, that would be awesome!

**Comment by florimondmanca** [comment]
Okay — created [heroku-example](../../heroku-example) and sent you an organization member invite. :wink:

**Comment by heykarimoff** [comment]
> By the way, did you try to deploy without setting `port=int(os.getenv("PORT"))`? As explained [here](https://bocadilloproject.github.io/guides/app.html#host-and-port), if the `$PORT` environment variable is set Bocadillo will use it along with `0.0.0.0` as the port. I configured it that way because in my memories this is what Heroku expects, but if that's not the case then we can consider it a bug. 😉

on my first push it gave me an error and I added this line. However I deployed without specifying any port and it works.

**Comment by florimondmanca** [comment]
I think it was because the host and port was bound via the gunicorn command, which you removed in the `$PORT` commit later on:

```
web: gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b localhost:8000 app:app --log-file - 
```

**Comment by heykarimoff** [comment]
@florimondmanca I see now. Thanks.
