### ISSUE TITLE
Autorefresh after a change to the static file

### ISSUE THREAD

**Issue by narslan** [bocadilloproject/bocadillo#179]
After a change to a css or js file under ´static´ folder, I have to restart the server(application) to make the changes effective. In other words, the changes to the static files during development are not immediately picked up by the application.   
My solution was to pass `autorefresh=True` to the constructor in `staticfiles.py`. 
Whitenoise still caches the files to an indefinite extent after that, but not too long. 
My question in this regard:
How can I truly make bocadillo instantly picking up the changes to the static files ?

**Comment by florimondmanca** [comment]
Hi! Thanks for reporting this issue.

I agree with you that being able to pick up static file changes during development would be nice!

The WhiteNoise [autorefresh](http://whitenoise.evans.io/en/stable/base.html#autorefresh) configuration attribute indeed seems to be what we're looking for. The docs read:

> This is designed to be used in development where it can be convenient to pick up changes to static files without restarting the server.

So I think it would be fair to automatically turn this on when running in debug mode, i.e. `app.run(debug=True)`.

Is there any chance you'd be willing to work on this yourself? 😄

**Comment by florimondmanca** [comment]
I'll go and release a fix for this. :-)

**Comment by narslan** [comment]
Thanks for the update. Please go for it. It is better that you take it over. It will be faster. I find your implementation idea at #180 nice.

**Comment by florimondmanca** [comment]
Done. This has just been released in v0.12.2 :+1: https://pypi.org/project/bocadillo/0.12.2
