### ISSUE TITLE
Uvicorn 0.5

### ISSUE THREAD

**Issue by tomchristie** [bocadilloproject/bocadillo#183]
Uvicorn 0.5 has been released.

* Auto-reloading will now take effect, without having to use `uvicorn` from the console.
* Multi-worker support is here.

I've just noticed you import `StatReloader` from uvicorn - which is technically private API - you'll find that's broken with the upgrade.

I'd suggest the following:

* Stop importing `StatReloader` - instead just use `reload=True` in `uvicorn.run(...)`
* Pin uvicorn to `0.5.*`
* If you want to enable multiworker support (it's not the default *yet*) then use `workers=multiprocessing.cpu_count()`.

**Comment by florimondmanca** [comment]
Hi @tomchristie, glad to know multi-worker support has arrived in Uvicorn. Thanks a lot for reporting this here. Will take a look at this soon!

**Comment by waghanza** [comment]
Hi @tomchristie, 

Do you plan top merge `uvicorn` with `gunicorn` ?

Now that `python` `2` is dropped ?

Regards,

**Comment by tomchristie** [comment]
@waghanza Not especially - I'd be totally happy for the ASGI worker class to be a built-in option for gunicorn, but I've no idea if there's any appetite for that.

**Comment by waghanza** [comment]
let's ask @benoitc to add `ASGI` support :stuck_out_tongue:

**Comment by florimondmanca** [comment]
@waghanza I'd personally be in favour of this too, but perhaps the discussion should be ported over the uvicorn/gunicorn repos. You may want to chime in here: https://github.com/benoitc/gunicorn/issues/1380 :wink:

**Comment by florimondmanca** [comment]
Deployed :tada: https://pypi.org/project/bocadillo/0.12.4/ Will add multi-worker in a future release.
