### ISSUE TITLE
'WebSocket' object has no attribute 'query_params'

### ISSUE THREAD

**Issue by cs01** [bocadilloproject/bocadillo#200]
**Expected behavior**

Query params are accessible

**Actual behavior**

Query params not accessible

**To Reproduce**

Request url `URL('ws://localhost:8000/command_terminal_from_browser?id=fa485e29114440e39c33e652d5234709')`

```

@app.websocket_route("/command_terminal_from_browser")
async def command_terminal_from_browser(ws):
    try:
        web_clients = set()
        async with ws:
            ws_id = ws.query_params.get("id", None)
...
```

**Screenshots/Traceback**

```
    ws_id = ws.query_params.get("id", None)
AttributeError: 'WebSocket' object has no attribute 'query_params'
```

![image](https://user-images.githubusercontent.com/5715368/54066927-70fa0980-41ed-11e9-9e57-0afc51acef5b.png)

**Possible solutions**

**Specs**
- OS + Version: Ubuntu 18.04
- Python Version: Python 3.6.7
- Bocadillo Version: bocadillo==0.12.2

**Additional context**

The guide mentions `ws.query_params`, but the example has `req.query_params`. Not sure if this is related.
https://bocadilloproject.github.io/guides/websockets/routing.html#query-parameters

**Comment by florimondmanca** [comment]
Yep, that's definitely a bug. Turns out we'll have the same issue with `headers` — it's not listed in your interpreter screenshot either.

Will look into it. In the meantime you can access them via `ws._ws.query_params` / `ws._ws.headers` (although this private interface may change with the fix). :+1:

**Comment by florimondmanca** [comment]
Patch released: https://pypi.org/project/bocadillo/0.12.6/ :+1:

**Comment by cs01** [comment]
So fast! Thank you!
