### ISSUE TITLE
Document cookie-based sessions

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#212]
See #211 (PR) and #6 (issue).

**Comment by florimondmanca** [comment]
Hey @zgoda, would you mind describing the kind of use case you were going for with cookie-based sessions? I'm investigating some security guidelines for the docs and an example use case could be useful. :-)

**Comment by zgoda** [comment]
I use sessions only to store authentication cookies/tokens, besides this I don't see much use for sessions these days. Cookie based implementation is simplest and does not require any specific support on backend.

**Comment by florimondmanca** [comment]
Thanks for your input!

> I was thinking on writing some documentation for this feature but it's too small for separate section, perhaps a paragraph or two in responses document?

I already took the leap and submitted this in #213. In particular, I included a caveat that since Bocadillo hasn't got any CSRF protection yet, from a security point of view I can't officially recommend to use cookies for session-based auth. Glad to have your thoughts!

**Comment by zgoda** [comment]
If I may suggest - there are HTML form/HTTP post data processing libraries that do CRSF right. Why not leave this to be done by them?

**Comment by florimondmanca** [comment]
Yes, we could very well reframe the caveat towards "Make sure you use a form library that handles CSRF". Do you have any libraries to recommend? :-)

**Comment by zgoda** [comment]
WTForms. Deform has one too but it's not as straightforward as in WTForms.

Anyway, with working session implementation CSRF protection is pretty simple, it's just passing token back and forth.

**Comment by florimondmanca** [comment]
Cool, thanks. I've ported this discussion to a separate issue to keep things organized: #215.

What I suggest is that we stick to the strong warning for now. If you're able to make CSRF work on your side by integrating with WTForms or another library, that's great. But until we have officially supported a CSRF protection mechanism built-in, we can't take the risk of telling people they should put user credentials in those easy-to-sniff cookies. :-)
