### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#215]
**Is your feature request related to a problem? Please describe.**

Bocadillo currently provides no CSRF protection mechanism. We've just merged in support for cookies (see #6), so we should definitely consider adding a token-based CSRF mitigation helper.

**Describe the solution you'd like**

TBD

**Describe alternatives you've considered**

TBD

**Implementation ideas**

TBD

**Additional context**

Discussion continued from #213

**Comment by florimondmanca** [comment]
@zgoda I've ported our discussion from #212 over here. :+1:

> WTForms. Deform has one too but it's not as straightforward as in WTForms.

I see. Ideally, we'd probably want CSRF protection not to depend on a third-party form library, and I think that this is doable.

> Anyway, with working session implementation CSRF protection is pretty simple, it's just passing token back and forth.

Yup, I had never looked at how CSRF protection was implemented before, but it seems pretty straight-forward. This old [Flask snippet](http://flask.pocoo.org/snippets/3/) gives a good idea of how that might be implemented. My guess is that an [HTTP middleware](https://bocadilloproject.github.io/how-to/middleware.html#http-middleware) could do the trick.

However, the snippet has several quirks that make it a) not directly applicable to Bocadillo (the `session` is attached to the request object) and b) insecure (we probably want to salt the token to prevent [BREACH](http://breachattack.com) attacks).

Probably a more inspiration-worthy implementation is that of [Django](https://github.com/django/django/blob/master/django/middleware/csrf.py).

I don't think the implementation would be *that* straight-forward, but I do agree that we should try and get something out for this.

**Comment by zgoda** [comment]
Django is large, monolithic, tightly coupled and provides everything you may need to do your web application, at least backend wise. It grew out of internet branch of local newspaper in some small town in Kansas, USA.

In another corner you have Flask which grew out of April Fools joke and just integrates couple projects by one man from Austria. And people started writing extensions to integrate other chunks of code with it.

It's really your choice - implement form processing on your own or go Flask way and let other people do that with extension/plugin/glue.

**Comment by florimondmanca** [comment]
There's probably a middleground to be found between the Django monolith and the Flask do-everything-else-yourself philosophy, especially when it comes to security. :-)

> implement form processing on your own

As a matter of fact, Bocadillo already has form parsing with `data = await req.form()`. This allows to inspect the contents of the HTML form sent by the client, regardless of any extra validation we may want to do (e.g. with WTForms, [TypeSystem](https://www.encode.io/typesystem), or any other validation library).

I'll quote Tom Christie's answer to https://github.com/encode/typesystem/issues/55 in which OP asked whether TypeSystem would allow to perform CSRF token checks:

> Short: Yes, but it’s the responsibility of Middleware, plus the developer including the CSRF token in the templates.

I agree with this, and I think CSRF token middleware (along with providing a `csrf_token` function in templates) is one of those things that we can have built-in without making any further assumptions on downstream form validation, which remains up to the developer.

Besides, I believe it's the framework's duty to make building secure apps easy out of the box. If this was released as an extension (even an official one), I'm afraid people would use forms *without* CSRF by default because, honestly, it's not the most user-friendly mitigation mechanism.

**Comment by florimondmanca** [comment]
This issue has gone stale — I'm closing it for now, as I don't think CSRF is still a need today.
