### ISSUE TITLE
'enable_hsts' results in TypeError: __init__() got an unexpected keyword argument 'enable_hsts'

### ISSUE THREAD

**Issue by cs01** [bocadilloproject/bocadillo#218]
**Expected behavior**
enable_hsts keyword arg can be passed to  `app.run()`

**Actual behavior**
`TypeError: __init__() got an unexpected keyword argument 'enable_hsts'`

**To Reproduce**
```
        server.app.run(
            host=args.host,
            port=int(args.port),
            ssl_certfile=args.certfile,
            ssl_keyfile=args.keyfile,
            enable_hsts=(args.certfile or args.keyfile),
        )
```
**Screenshots/Traceback**
```
>> termpair serve --port 8001
Traceback (most recent call last):
  File "/home/csmith/git/termpair/venv/bin/termpair", line 11, in <module>
    load_entry_point('termpair', 'console_scripts', 'termpair')()
  File "/home/csmith/git/termpair/termpair/main.py", line 95, in main
    enable_hsts=(args.certfile or args.keyfile),
  File "/home/csmith/git/termpair/venv/lib/python3.6/site-packages/bocadillo/applications.py", line 515, in run
    _run(target, host=host, port=port, **kwargs)
  File "/home/csmith/git/termpair/venv/lib/python3.6/site-packages/uvicorn/main.py", line 249, in run
    config = Config(app, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'enable_hsts'

```
**Possible solutions**

**Specs**
- OS + Version:
- Python Version: 3.6
- Bocadillo Version: bocadillo==0.12.6

**Additional context**

uvicorn==0.5.2

**Comment by florimondmanca** [comment]
Hi Chad, `enable_hsts` is a parameter for the `App` class, not `app.run`, as described here: [HSTS](https://bocadilloproject.github.io/guides/app.html#hsts).

If you absolutely need to conditionally enable HSTS at runtime, you can still add the `HTTPSRedirectMiddleware` yourself:

```python
from starlette.middleware.httpsredirect import HTTPSRedirectMiddleware

app.add_asgi_middleware(HTTPSRedirectMiddleware)
```

**Comment by florimondmanca** [comment]
Makes me wonder if it would be worth moving the `enable_X` instanciation-time parameters to instance attributes, e.g. something like:

```python
from bocadillo import App

app = App()
app.enable_cors = True
app.cors_config = {"allowed_hosts": [...]}
app.hsts = True
```

And then only add the middleware in `app.run()` based on those flags and config attributes.

**Comment by cs01** [comment]
> Hi Chad, enable_hsts is a parameter for the App class, not app.run, as described here: HSTS.

Thanks, the search for the docs wasn't working so I just assumed it was passed in like the other parameters

I would definitely like the option to be able to modify the instance after it's been created. For now I'll go with the middleware route as you described. And thank you for anticipating my desire to do that :smile: .
