### ISSUE TITLE
Typo in the example code in Quick start section

### ISSUE THREAD

**Issue by heykarimoff** [bocadilloproject/bocadillo#222]
**Expected behavior**

It should run Uvicorn running on http://127.0.0.1:8000

**Actual behavior**

Throwing `NameError: name 'app' is not defined` error.

**To Reproduce**

Paste Quick start snippet in app.py and run `python app.py`

**Screenshots/Traceback**

```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    app = app()
NameError: name 'app' is not defined
```

**Possible solutions**

Update line 3 to correctly use `App`
```
from bocadillo import App

app = App()    # <- here

@app.route("/")
async def index(req, res):
    res.text = "Hello, world!"

if __name__ == "__main__":
    app.run()
```
**Specs**
- OS + Version: macOS Mojave 10.14.3
- Python Version: 3.7.2
- Bocadillo Version: 0.13.0

**Additional context**

**Comment by florimondmanca** [comment]
Oops! That's indeed a typo. Thanks for spotting it!

I see you committed a fix to your fork. If you submit a PR be sure to branch off from `release/docs` instead of `master` so we can deploy the docs fix right away. :+1:

**Comment by florimondmanca** [comment]
Nevermind, I thought this was in the docs' `README.md`, but it's the one from the repo. 🤦‍♂️ 

Anyway, feel free to open a PR with your fix. :-)
