### ISSUE TITLE
Module-based route discovery

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#234]
**Is your feature request related to a problem? Please describe.**

When #117 is resolved, we won't have any means of defining a set of routes to be mounted onto an app while preserving the app's configuration, i.e. not defining a separate, independent app.

**Describe the solution you'd like**
Allow to load routes from Python modules:

```python
# items.py
from bocadillo import route

@route("/")
async def index(req, res):
    ...
```

```python
# app.py
from bocadillo import App
import items

app = App()
app.discover_routes(items, prefix="/items")
```

**Describe alternatives you've considered**

- Add support for other namespaces than modules (e.g. classes or objects): poor semantics.
- Recursive discovery (i.e. load all routes within a package): will probably be implemented later.

**Implementation ideas**

Expose package-level `route` and `websocket_route` decorators that create `HTTPRoute` and `WebSocketRoute` objects, then filter for those on the module given to `.discover_routes()`.

**Additional context**

/

**Comment by Marlysson** [comment]
Each file will be as a namespace...Separating each ones in a file?

**Comment by florimondmanca** [comment]
Well, that's pretty much the idea. This allows to split routes into small logical pieces with a clear boundary of what is possible — i.e. define routes and that's it. If you need to configure anything else (middleware, error handlers, …), you'd need to create a separate `App` and `.mount()` it instead.

Thoughts? :-)

**Comment by Marlysson** [comment]
Yup!! This was the first idea that came to my mind ...

> Thoughts? :-)

Everything it's very well explained haha.. I'm seeing the code base..  whether exist something to do here, let me know 😄 .. The codebase grew so fast

**Comment by florimondmanca** [comment]
I am closing this in favor of #261 which I believe to be a more sustainable and scalable solution to write larger apps.
