### ISSUE TITLE
Add tutorial(s)

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#25]
**Is your feature request related to a problem? Please describe.**
If I were someone getting started with Bocadillo, I'd be pretty sad seeing that only specific how-to and API guides are available.

**Describe the solution you'd like**
I'd need a tutorial to take me through building something with Bocadillo, and get a feel for what it has to offer.
Note: this differs from a "quick start" guide that explains what the most important available features are and how to use them.

**Describe alternatives you've considered**

One possible application could be that of a blog:
- CRUD operations with templates
- Demonstrates routing, templating, forms, error handling
- It would be nice to show an integration with an SQL library, like `sqlite3`, without spending too much time on it though.

Another option could be a mailer service:
- No database involved, sending emails would be mocked.
- `POST` endpoint to send an email
- `GET` endpoint to check service health
- Demonstrates routing, working with JSON, API forms and validation

Yet another option to demonstrate using Bocadillo for async stuff is building a simple web crawler (see [Tornado](https://www.tornadoweb.org/en/stable/guide/queues.html)'s tutorial).

**Additional context**
This is a TODO item in the docs. It's high priority because it's hindering getting people (especially beginners) to use the framework.

**Comment by bevennyamande** [comment]
How can i get started

**Comment by florimondmanca** [comment]
Hi @bevennyamande , thanks for popping by!

So should I understand you'd be willing to draft a tutorial?
If you've tried Bocadillo out already, would you want to pick up any of the ideas listed in the issue description?

**Comment by florimondmanca** [comment]
I'm taking on writing the web spider/crawler tutorial. 🕸  New repo: [tarantula](https://github.com/bocadilloproject/tarantula).
