### ISSUE TITLE
installation fails for dependent package httptools

### ISSUE THREAD

**Issue by cs01** [bocadilloproject/bocadillo#269]
Installing bocadillo-0.15.0 with a new python version on my machine fails to install. After investigating, it's because httptools requires python-dev to be installed for each version of Python. See https://github.com/MagicStack/httptools/issues/33. Bocadillo's docs should cover this.

**Comment by florimondmanca** [comment]
Hey, thanks for reporting this!
Which version of Python are you using? So you had to install python-dev for the other version too?

**Comment by cs01** [comment]
Was using python3.6, now using python3.7.
