### ISSUE TITLE
Allow extra headers in HTTPError

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#275]
**Is your feature request related to a problem? Please describe.**
We may want to send extra headers along with the response when an HTTP error occurs — particularly when dealing with authentication. We cannot do so currently without writing a custom error handler that would define the format of the response (plain text, JSON, …).

**Describe the solution you'd like**
Add a `headers` parameter to `HTTPError`, which users/clients can use to define extra headers to be sent with the response.

**Describe alternatives you've considered**
- Refactor `HTTPError` to be a subclass of Starlette's `HTTPException` (see #274), and push this feature to the upstream Starlette project => incompatible with the philosophy of Starlette as an ASGI toolkit - see https://github.com/encode/starlette/pull/507.

**Implementation ideas**
We'll need to update the base error handlers (`error_to_text`, `error`to_json`, etc) to send the extra headers with the response.

**Additional context**
/

**Comment by teaglebuilt** [comment]
is this feature still open?

**Comment by florimondmanca** [comment]
Hi @teaglebuilt,

Despite #334, yes it is. I would gladly review a PR to implement this piece of functionality. :)
