### ISSUE TITLE
Bocadillo CLI generated code vs. guides

### ISSUE THREAD

**Issue by EricE** [bocadilloproject/bocadillo#277]
**Is your feature request related to a problem? Please describe.**
The workflow described in the guides doesn't work exactly as shown if you started with an app generated by the CLI.  For instance, https://bocadilloproject.github.io/guides/architecture/app.html#configuration  If you used the CLI, configuration is handled in asgi.py and you get an error if you try to mirror the code shown in the guide.  This is the second case I've found, would it be useful to change the guides to assume that the user started with the CLI or comment that the cli code shows an alternative approach where necessary?

**Comment by florimondmanca** [comment]
Yes, interesting one.

The goal of the CLI is to help standardize project structure and implement best practices.

I don’t want to lock people down and require them to use the CLI structure. People should still be able to write everything in a single module if they wanted to. Besides, this encourages decoupling of components in the framework code.

That’s why the configuration guide starts with a single script, and expands to eventually get to what the CLI generates (app.py, settings.py, asgi.py) — *except* that the CLI puts code in a package, which definitely becomes confusing when trying to adapt snippets from the docs to a CLI project.

So, options:

1. Include two examples each time, one with the CLI (or « package style » and one without (« module style »).
2. Assume that people use the CLI by default (everywhere in the docs), and create an advanced section in the Apps docs about module-style projects.

I think 2) would be a good way to go, what do you think?

**Comment by EricE** [comment]
Sorry got pulled away.  I like option 2 as well.  It is easy to run the CLI to get the basic setup and it encourages good organization of the files.

**Comment by florimondmanca** [comment]
I am tackling this in #263. :-)

**Comment by florimondmanca** [comment]
@EricE I've just released an overhaul of the documentation, which includes a more consistent usage of a project structure similar to what Bocadillo CLI generates.

Basically, all code snippets now show scripts located in a package (e.g. `# myproject/app.py`), and [Applications](https://bocadilloproject.github.io/guide/apps.html) now explicitly recommends to use this package-style project structure.

Feel free to skim through the [guide](https://bocadilloproject.github.io/guide) and share your thoughts!

I'm closing this for tidying purposes, but the discussion can continue. :-)
