### ISSUE TITLE
Add a Vue frontend framework example

### ISSUE THREAD

**Issue by EricE** [bocadilloproject/bocadillo#307]
**Is your feature request related to a problem? Please describe.**
Only have a React example, it would be great (for me at least :)) to have a Vue example

**Describe the solution you'd like**
Add a Vue.js example to the frameworks page

**Describe alternatives you've considered**
NA

**Implementation ideas**
Unfortunately I don't know Vue so need somebody else to do the work

**Additional context**
NA

**Comment by AkumaBugs** [comment]
This is a fine idea. I am a beginner at both python and Vue and a simple app showing Bocadillo with Vue frontend would be really sweet. It could be as simple as  just hello app or even something like to do list combined with authentication and sqlite DB. 

So far I really love the documentation, but I miss that authentication part with multiple possible roles or something that can restrict route access.
Anyway, Bocadillo is something that I really like and love following and reading through on my spare time even though I don't program much. Keep up the good job. Thanks for your hard work.

**Comment by florimondmanca** [comment]
Very good idea!

I’m not sure there’s any specificity to using Vue/React with Bocadillo (assuming Bocadillo is used to provide a REST API of some sort), but I think just having these examples available for showcase/template is a pretty sensible idea.

I’m a Vue user myself and should have a bit of time available to give this a shot. Might as well turn this into a « Build a todo app with Bocadillo and Vue » blog post aimed at beginners at any of these technologies. :)

Also thanks for the kind words @AkumaBugs! I appreciate it a lot. :) Authentication and permissions are in the roadmap (#100).

**Comment by florimondmanca** [comment]
So, I've already got a very basic setup over https://github.com/bocadilloproject/vue-example.

I listed a few things I think would be interesting to tackle in the `ROADMAP.md` file. :+1:

**Comment by florimondmanca** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [URL Shortener tutorial (Bocadillo + Vue)](https://trello.com/c/L8YXvasK/6-url-shortener-tutorial-bocadillo-vue)

**Comment by florimondmanca** [comment]
The Vue example repo now features a full-blown URL shortener app *including* an SQLite DB for storing link hashes! https://github.com/bocadilloproject/vue-example

Demo gif:

![](https://github.com/bocadilloproject/vue-example/raw/master/media/demo.gif)

It's been added to the frontend guide as well: https://bocadilloproject.github.io/discussions/frontend.html

Let me know what you think, and whether this addresses the initial need. If so, we can mark this a resolved! :tada:

**Comment by EricE** [comment]
Looks good, thanks for the quick response.  You are spoiling us :smile:
