### ISSUE TITLE
Async HTTP libraries

### ISSUE THREAD

**Issue by EricE** [bocadilloproject/bocadillo#318]
Question asked here instead of on Gitter :smile:
Getting back to my project and curious if there is a recommendation for an async lib for making http requests?  Seems like there is a lot of churn atm*.  Had started with requests-async but they now point to http3, there is aiohttp and probably others.  My use case is for the user to select/enter options and submit a form that causes 10's of requests that can go out in parallel.  The returned data is crunched (can take seconds) and the UI updated (seems like a good use case for websockets?).  I'm leaning towards HTTP3 (I had gotten oauth2 working with requests-async) but before I get to far I figured I check with the experts.
'* https://github.com/encode/http3/issues/78

**Comment by florimondmanca** [comment]
Hey :)

I think http3 is the good way to go. I’m pretty confident as to where the project is going and how Tom is handling it. Before the http3 rebrand I would have recommended requests_async anyway! (aiohttp is fine as well, but I personally don’t like the context manager-based API that much.)

> 10's of requests that can go out in parallel

http3 has a pretty cool .parallel() API which might be perfect for this use case!

> The returned data is crunched (can take seconds)

Sounds like a good fit for the threadpool trick :)

> the UI updated (seems like a good use case for websockets?)

I’m not sure to be honest. If the UI is a JS frontend, then it’s asynchronous already and it should simply update when it receives a response from the server. Or are you handling the UI differently?

**Comment by EricE** [comment]
I'm leaning towards learning Vue which is why I asked for an example :smile:  I have to admit that the data flow between the server and Vue is still a mystery, I'm taking it on faith atm that there is a way to make it work.

**Comment by florimondmanca** [comment]
Yes, I think once you have the API endpoint ready most of it happens in the browser.

In my experience, the general flow for making API calls in Vue (or any other frontend framework with slight variations) is the following:

1. User performs an action (eg click on a button).
2. An event listener registered on the element (eg v-on:click pointing to a method on the component) is triggered.
3. The method performs an HTTP call to the server, eg using the standard fetch() API or a library like axios, and registers a callback to be called when the response has been received.
5. The server processes the request and sends a response.
6. The frontend receives the response and calls the callback registered earlier.
7. In the callback, we do any updates we need to do, eg change data on the component, navigate to another page, etc.

Note that the terms “component”, “method”, “event listener”, “data” have a special meaning in Vue - very well explained in the official docs.

Also I think you can find code examples (and even tutorials) for this quite easily. :) If you need any help integrating http3 into the endpoint, let me know! I’d also be interested to see how it looks in the end. :)

**Comment by EricE** [comment]
Thanks for the mini-tutorial, I'll keep going with http3.
