### ISSUE TITLE
Constraint on route

### ISSUE THREAD

**Issue by waghanza** [bocadilloproject/bocadillo#321]
Hi,

It could be useful to constraint a route. 
It could be done by a regex (or any other technique).

It could mimic, `flask` **decorator**
~~~python
@app.route("/user/<int:id>", methods=["GET"])
~~~

Regards,

**Comment by florimondmanca** [comment]
Hi, thanks for this!

Bocadillo already supports validation of route/query parameters via type annotations — see: https://bocadilloproject.github.io/guide/routing.html#validation-and-conversion

Does this fit your use case?

I don’t think TypeSystem (which Bocadillo uses internally to perform validation) does not support arbitrary regex validation yet, so if that’s what you need then we could consider opening an issue/PR there. :)

**Comment by waghanza** [comment]
Hi @florimondmanca,

It OK for me. 

My needs was :

+ casting : having an `int` instead of a `string`
+ root filter
   + /items/a => 4xx
   + /items/a1 => 4xx
   + /items/1a => 4xx
   + /items/1 => 2xx
