### ISSUE TITLE
OpenAPI/Swagger libraries

### ISSUE THREAD

**Issue by EricE** [bocadilloproject/bocadillo#324]
Another not asked on Gitter question :smile:   I've looked for an async version of a swagger client, anybody have a recommendation?  I've found https://github.com/sjaensch/aiobravado  and https://github.com/swagger-api/swagger-codegen .  Swagger-codegen looks more complicated but maybe easier to keep up-to-date?

**Comment by florimondmanca** [comment]
Hey! It’s an interesting one. :) Just to be sure, are you looking for a library that would generate an async client (either as code or as on-the-fly generated objects) from an OpenAPI specification? The two libraries you’ve linked to seem to kind of fit this use case.

Also, is this anywhere related to Bocadillo? I’ve actually started experimenting with OpenAPI support (schema and docs generation!), and it could very well become a thing! But this would be the other way around: generating the OpenAPI schema from an application.

**Comment by EricE** [comment]
This is for a client, my Bocadillo site would be pulling data from an OpenAPI site that it then crunches and displays.  So the only association with Bocadillo is that it needs to integrate nicely.  It seems like they should but the codegen approach in particular is new to me so I thought I'd check to see if there was any experience with them.
