### ISSUE TITLE
Just a question about this framework

### ISSUE THREAD

**Issue by Danissss** [bocadilloproject/bocadillo#332]
Hi, great work on this light framework! I am learning how to build a framework myself and found this very useful!

From the `routing.py`, I found following import:
```
from .app_types import ASGIApp, EventHandler, Receive, Scope, Send
from .config import settings
from .errors import HTTPError
from .redirection import Redirect
from .urlparse import Parser
from .views import View
from .websockets import WebSocket, WebSocketView
```
May I ask what are these import that start with "." ?
Thanks!

**Comment by florimondmanca** [comment]
Hi, thanks for your kind words!

Those dots indicate imports relative to the package of the current Python module. To learn more about absolute vs. relative imports, I recommend this Real Python article: https://realpython.com/absolute-vs-relative-python-imports/

**Comment by Danissss** [comment]
Hi Thanks for the link!
Never thought use . to import the file in the same directory. 
Thanks!
