### ISSUE TITLE
Ending the project + Winding down plan

### ISSUE THREAD

**Issue by florimondmanca** [bocadilloproject/bocadillo#334]
Bocadillo development has slowed down dramatically in the past few months.

There are multiple reasons to this:

- My open source portfolio has grown substantially, meaning I have to prioritize which projects I dedicate my (free) time to.
- While building Bocadillo was a fun and enriching experience, I'm now having a hard time justifying its existence. There are already well-functioning async frameworks out there whose feature set often coincides a lot with Bocadillo's — Starlette and FastAPI come to mind. It would probably be a better approach to help build and expand those instead.
- I don't have a use case for Bocadillo in my day-to-day activities, which means I am not personally incentivized to keep working on it.

Although the number of starts keeps slowly increasing, which seems to indicate the project still generates *some* interest, there are hints that Bocadillo is a dying project.

As of today, all the warning signs from the following quote ([source](https://www.linuxfoundation.org/resources/open-source-guides/winding-down-an-open-source-project/)) seem to apply to Bocadillo:

> "If you don’t have anybody asking questions, if nobody’s making contributions, if there doesn’t seem to be any new adoptions, nobody seems to be adding dependencies, and if you’re not seeing any other signs the people are using it, that’s a potential big warning sign. It may all be fine, but it’s worth checking to see if the project is dying.”

There hasn't been any new issues, any new PRs, and the [dependants page](https://github.com/bocadilloproject/bocadillo/network/dependents?package_id=UGFja2FnZS0yMDQ5OTkwNDU%3D) hasn't grown in the past few months. (Besides, it only contains hello world projects.)

As a matter of fact, Bocadillo has become a burden to me. Yet, open source should never become a burden — but I don't have the resources nor the motivation to revive the project.

All of this leads me to consider ending Bocadillo as an open source project.

In terms of roadmap, this would happen in two stages:

1. Entering maintenance mode (planned mid-October, 2019):
  - No new features, only critical bug fixes.
  - Users will be encouraged to switch to a well-supported alternative, such as Starlette or FastAPI.
  - [x] This requires some changes to the README and the documentation site (e.g. a clearly visible banner). The aim is to make the intent to end the project clear.
2. Archiving the project (planned mid-November, 2019):
  - Marking the repo and the docs as read-only.
  - Anyone interested could still fork the repo if needed, or reuse/reference parts of the code for other use cases.
  - The documentation site will probably stay up as it doesn't cost me anything.

(The other alternative is to transfer the project to someone else. Since there aren't any active community members I know of, I don't know if anyone would be interested in taking it over.

Yet, if you are reading this and would like to take over the maintenance and/or development of Bocadillo, let's get in touch! I am [FlorimondManca](https://twitter.com) on Twitter.)

**Comment by prostomarkeloff** [comment]
:sob:

**Comment by RodolfoFerro** [comment]
:(

**Comment by richardnpaul** [comment]
I totally understand this stance.  I have come back here fairly frequently to see updates, and I was interested that this project was name dropped by Tom Christie in a conference earlier this year, so people are aware of it at least.

Good luck in your future open source adventures @florimondmanca and thanks for opening our eyes :)

**Comment by florimondmanca** [comment]
Announcements just published on Twitter:

- https://twitter.com/bocadillopy/status/1188896193427972097
- https://twitter.com/florimondmanca/status/1188899133656064005

**Comment by waghanza** [comment]
I'd enjoy you work @florimondmanca, and I'll retire it from https://github.com/the-benchmarker/web-frameworks :1st_place_medal:

**Comment by florimondmanca** [comment]
Thanks @waghanza! Good point, I forgot it was still listed on there. :-) Keep up the great work there!

**Comment by florimondmanca** [comment]
Alright, now that references to Bocadillo in upstream/downstream projects seem to be gone, and there's been plenty of time since the initial announcement here, I am officially going to archive the repository.

Thanks everyone for your support! Keep building cool things.
