### ISSUE TITLE
Add support for any ASGI middleware

### ISSUE THREAD

**Issue by alin23** [bocadilloproject/bocadillo#47]
**Is your feature request related to a problem? Please describe.**
Before the rewrite of the middleware system, `add_middleware` worked with ASGI middleware seamlessly. Now it doesn't work anymore.

**Describe the solution you'd like**
Implement an `add_asgi_middleware` to support that.

**Describe alternatives you've considered**
None

**Additional context**
There aren't many ASGI middlewares out there, but those that exist are important and I guess nobody would want to write that code twice instead of just using a lib. Also ASGI is gaining popularity, maybe more middlewares will pop up.

**Comment by florimondmanca** [comment]
Just to be sure, is this about the fact that middleware classes implementing the ASGI protocol directly are not supported anymore? If so, that's actually a good point. I think we could repurpose the `_starlette_middleware_chain()` method to register ASGI middleware there.

**Comment by alin23** [comment]
Yes, it's about that. I thought about creating a separate function since ASGI middlewares are not only found in Starlette

**Comment by florimondmanca** [comment]
Sure. The middleware rewrite has not been released yet solLet's get this in v0.7.
