### ISSUE TITLE
Update documentation for background tasks examples (and maybe other examples as well)

### ISSUE THREAD

**Issue by jpmelos** [bocadilloproject/bocadillo#89]
The documentation should use the new API for `@api.route` and `@view`. It currently uses an example in [Creating a background task](https://bocadilloproject.github.io/guides/http/background-tasks.html#creating-a-background-task) that violates that:

```python
from asyncio import sleep

@api.route('/orders', methods=['post'])
async def create_order(req, res):
    @res.background
    def send_confirmation():
        # TODO: send an email here
        await sleep(1)

    res.status_code = 201
```

I guess it should be:

```python
from asyncio import sleep

@api.route('/orders')
@view(methods=['post'])
async def create_order(req, res):
    @res.background
    def send_confirmation():
        # TODO: send an email here
        await sleep(1)

    res.status_code = 201
```
As explained in [Specifying HTTP methods](https://bocadilloproject.github.io/guides/http/routing.html#specifying-http-methods).

Is this correct? There might be other API mistakes in the documentation.

**Comment by florimondmanca** [comment]
Thanks for spotting this! This is indeed an artifact from the old API that should have been updated.

**Comment by florimondmanca** [comment]
Done — I've fixed the background tasks examples, and this also had an occurrence in the Responses section. Thanks again for reporting this!

https://bocadilloproject.github.io/guides/http/background-tasks.html#how-do-background-tasks-work
