### ISSUE TITLE
Update docs for api.route removed `methods` argument

### ISSUE THREAD

**Issue by cmin764** [bocadilloproject/bocadillo#91]
In version 0.9.1 remove this part from `bocadillo.api.route` method:

```python
methods (list of str):
            An optional list of HTTP methods.
            Defaults to `["get", "head"]`.
            Ignored for class-based views.
```
as `methods` keyword argument was moved to the `bocadillo.views.view` function.

**Comment by florimondmanca** [comment]
[Fixed](https://bocadilloproject.github.io/api/routing.html#route), thanks for spotting this out!
